services:
  sss-front:
    build: ./sss-front
    container_name: sss-front-showroom
    restart: always
    ports:
      - '5175:5174'
    volumes:
      - ./sss-front:/usr/src/app
    env_file:
      - ./sss-front/.env.showroom
    environment:
      - NODE_ENV=development