# fly.toml app configuration file generated for super-secret-samples on 2025-09-16T14:02:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'super-secret-samples-showroom'
primary_region = 'cdg'

[build]
dockerfile = "Dockerfile.prod"

[deploy]
#release_command = "npx prisma migrate deploy"

[http_service]
internal_port = 5174
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[checks]
[checks.alive]
grace_period = "30s"
interval = "15s"
method = "GET"
path = "/"
port = 5174
timeout = "10s"
type = "http"